### ISSUE TITLE
Bot crashes when there is a collision

### ISSUE THREAD

**Issue by timopomer** [skzgv/bot#2]
we are getting ArrayList Comodifications. fix please

**Comment by ptzafrir** [comment]
I think the idea of available pirates is redundant and causing problems. you can have the main doTurn with myPiratesWithTreasures -> go home. myPiratesWithoutTreasures -> get treasures.
removing the available pirates will fix this issue as well

**Comment by ptzafrir** [comment]
if you can specify which simulation you ran, in which turn it crashed, and copy the exception message, it can help others reproduce and fix the problem

**Comment by timopomer** [comment]
i like that idea. maybe that will change/fix the problem aswell. i didnt know java can Co-modify its own variables anyways.

now pushing new moveToClosestTreasure() that fixes some issues i had

**Comment by timopomer** [comment]
right.

`C:\Users\timop\Desktop\skillz\starter_kit>run C:\Users\timop\Desktop\skillz\starter_kit\bots\java\MyBot.java C:\Users\timop\Desktop\skillz\starter_kit\bots\demoBot4.py C:\Users\timop\Desktop\skillz\starter_kit\maps\default_map.map
turn #0 of max 1000
turn   13 bot demoBot4 Debug prints:
Debug>> WARNING: Pirate 2 tried to set sail to its current location.
turn   14 bot MyBot Debug prints:
Debug>> WARNING: Pirate 2 tried to set sail to its current location.
turn   20 bot MyBot Debug prints:
Debug>> WARNING: Pirate 2 tried to set sail to its current location.
turn #20 of max 1000
java.util.ConcurrentModificationException
        at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
        at java.util.ArrayList$Itr.next(ArrayList.java:851)
        at bots.MyBot.doTurn(MyBot.java:44)
        at pirates.runner.JavaRunner.run(JavaRunner.java:122)
        at pirates.runner.JavaRunner.main(JavaRunner.java:162)
turn   26 bot 0 crashed
score 2 2
player 2 [demoBot4] is the Winner!
`


demobot4, causes the crash immediately when they collide at turn 26

**Comment by timopomer** [comment]
i know what causes the issue.

we are changing a list while iterating thru it. specifically availablePirates. i will do some patching. i think availablePirates isnt necessary at all because there is no reason a pirate should be "unavaible" unless he is dead. which we can check. or drunk. which we can check!

**Comment by timopomer** [comment]
fixed
